spring:
  datasource:
    url: jdbc:mysql://database-1.cacec1zyjyww.us-east-2.rds.amazonaws.com:3306/testdb
    username: admin
    password: gReEMtJmVyswTqQ6bnBu
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: db/liquibase.xml
    enabled: true

cloud:
  aws:
    region:
      static: us-east-2
